require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/*
    - vendor/**/*
    - tmp/*
    - config/**/*
    - config.ru
    - Rakefile

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExpectActual:
  Exclude:
    - spec/routes/**/*

RSpec/VerifiedDoubles:
  Exclude:
    - spec/support/controller_helpers.rb

Metrics/AbcSize:
  Exclude:
    - spec/support/controller_helpers.rb
